// @ts-nocheck
// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type AppError = { RequestError: string } | { InvalidUrl: string } | "Timeout" | { NetworkError: string }

export type HttpRequestData = { method: string; url: string; headers: KeyValue[]; query_params: KeyValue[]; body: RequestBody }

export type HttpResponseData = { status: number; status_text: string; headers: KeyValue[]; body: string; size_bytes: number; time_ms: number }

export type KeyValue = { key: string; value: string; enabled: boolean }

export type RequestBody = "None" | { Json: string } | { FormUrlEncoded: KeyValue[] } | { Raw: { content: string; content_type: string } }

const ARGS_MAP = { '':'{"send_request":["request"]}' }
export type Router = { "": {send_request: (request: HttpRequestData) => Promise<HttpResponseData>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
